# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: '' # the base hostname & protocol for your site

title: 'Vishal Pani'
author: 'Vishal Pani'

languages: [ 'en' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '131006004@N06'
flickr_api_key: adb4be93419edab991522b4fa92b7029

default_header_img_dimensions: 'width="720 height="720"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Vishal Pani, a senior at IIIT-Allahabad interested in the intersection of Deep Learning and Computer Graphics. It enlists his projects, blog, and contact information.'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed
